### ISSUE TITLE
Why have new versions of Analytics.NET been in alpha for two years?

### ISSUE THREAD

**Issue by NatElkins** [segmentio/Analytics.NET#102]
See here: https://www.nuget.org/packages/Analytics/

Look at version history.

For people using .NET Core (pretty much all new greenfield development) they're going to get warnings like this:
```
 [NU1701] Package 'Analytics 3.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

It's been two years, might as well take the alpha off.

**Comment by ckuehl** [comment]
Any updates on this? It's not super confidence-inspiring for someone integrating for the first time to see this little activity over the last couple of years.

I'm currently deciding whether to just hit the Segment HTTP API directly with one of the well-known .Net Core libraries or to test one of the alpha versions of this library.

**Comment by guylando** [comment]
+1

**Comment by worldspawn** [comment]
@cgalan-applaudostudios your customers would a library that is 
a) less than 2 years old
b) not an alpha

**Comment by lubird** [comment]
As you can see from recent commits, we are still actively supporting this library with bug fixes and feature additions. There is a queue of changes we are planning to integrate into a new Nuget package soon.

We do have long term plans to address the .NET Core issues you mentioned, but I don't have timelines right now to speak of.

**Comment by rgwood** [comment]
Has anyone found a decent 3rd party .NET Segment library? Given that this library hasn't received a non-beta release in over 3 years, I'm looking to move away from it.

**Comment by nd4p90x** [comment]
We are moving to create a non-beta as we speak.  We are also working toward DI and working other open issues.  Please be patient with us as we make this transition as we want to get it right.  The current beta release, as stated above, is still actively supported and will continue to be, up to the next major release.  Thank you.

**Comment by nd4p90x** [comment]
On Wed 12/09/2020 we release out of Beta.  Sorry for the delay.  #152
