### ISSUE TITLE
3.4.1-alpha tag not found

### ISSUE THREAD

**Issue by mabead** [segmentio/Analytics.NET#139]
On nuget.org, I see that the latest version of the library is 3.4.1-alpha. Unfortunately, there is no tag in github for this version. It is therefore impossible to look at the code at this exact version:

```
> git tag --list
2.0.0
2.0.1
2.0.2
2.0.3
3.0.0
3.1.0-alpha
3.2.0-alpha
3.3.0-alpha
3.3.1-alpha
3.4.0-alpha
```

**Comment by pascalmartin** [comment]
Maybe is now a branche and not a tag
[https://github.com/segmentio/Analytics.NET/tree/releases/3.4.1-alpha](https://github.com/segmentio/Analytics.NET/tree/releases/3.4.1-alpha)

**Comment by lubird** [comment]
This was a miss on our end. Our latest release 3.4.2-beta has a proper tag now.
