### ISSUE TITLE
Inverted logic for "send"

### ISSUE THREAD

**Issue by mabead** [segmentio/Analytics.NET#140]
I mus admit that having `send=false` that means "don't don't send the data to segment = send the data to segment" is pretty confusing. 

Please make it simple to understand `send=false` should mean "do not send". The default parameter should therefore by `send=true`.

![image](https://user-images.githubusercontent.com/4930754/83868332-b0691b80-a6f8-11ea-9919-75aa086d4815.png)

**Comment by lubird** [comment]
You're correct! It does seem like it was inverted halfway through. Do you mind submitting a PR for this fix?

**Comment by mabead** [comment]
Sorry @lubird but since Segment is a product that we pay for, I am not very keen on submitting PRs.
