### ISSUE TITLE
Assembly not signed

### ISSUE THREAD

**Issue by OlegKravets** [segmentio/Analytics.NET#148]
Why is the assembly (Analytics.dll) not signed?

**Comment by juliette-ruchel** [comment]
This video shows the assembly signing and the creation of the key file with a test assembly. Please note that whoever signs the assembly must have administrator permissions or run visual studio as an administrator
https://drive.google.com/file/d/16u6cy6mnCGMSpcQ1qgALO74LNAbcUwDL/view?usp=sharing
