### ISSUE TITLE
Retroactive events

### ISSUE THREAD

**Issue by Lobosque** [segmentio/Analytics.NET#160]
How do I track events retroactively?

eg. I want to send now an event that happened last week

**Comment by juliette-ruchel** [comment]
According to documentation: https://segment.com/docs/connections/sources/catalog/libraries/server/net/#historical-import
There is a way of setting the timestamp of events. Tested it this morning with an test app and worked as expected.
However, as the documentation states, even though we send an old timestamp it might depend on the destination on how it's handled.

Here's an example of how they event was received when I tested it:
![issue 160](https://user-images.githubusercontent.com/73245018/109699955-f65fec80-7b6f-11eb-905a-a1c986a54027.png)

**Comment by nd4p90x** [comment]
@juliette-ruchel thank you for that response.  
@Lobosque let us know if you have any other questions regarding this issue.  
Thanks
