### ISSUE TITLE
Using Segment.NET Library on F# Project

### ISSUE THREAD

**Issue by juliette-ruchel** [segmentio/Analytics.NET#166]
An example of Segment.NET library being used on an F# project should be developed in order to understand it can be called perfectly well with its different functions

**Comment by juliette-ruchel** [comment]
Here is a link with a demo F# Console App showing how Segment .NET library works perfectly with it:

[(https://drive.google.com/file/d/1K1_NAVn8-NpWZKb6JqasxVUr_9mBG6V-/view)]

**Comment by nd4p90x** [comment]
@juliette-ruchel Thank you, the docs are being updated to reflect this addition.
