### ISSUE TITLE
[Question] is Flush called every 10 seconds by default?

### ISSUE THREAD

**Issue by pmahend1** [segmentio/Analytics.NET#169]
We are using this nuget in our xamarin app. Wanted to know if we should explicitly call Flush/FlushAsync on user logout.

Looks like its being called with timer every 10 seconds for async mode = True config.

We had Flush but that is blocking UI thread so was about to change it to Asynchronous , but we can omit it if its being called iteratively and has no impact on user logout and new user login or same user login again.

**Comment by juliette-ruchel** [comment]
Hi @pmahend1, in Analytics.NET library Actions are flushed once they reach the MaxQueueSize that is set for the Queue of Actions. This happens only if the library is set to async mode in true, if not it will try to send the action to the segment server inmediatly. 

By default the MaxQueueSize is set to 10000 which means that once you add 10000 actions to the queue it will try to send the actions to segment server. You can configure this MaxQueSize with the function SetMaxQueueSize of the Config class.
Regarding setting the async mode to true, I suggest you do it as if you do not, it will try to send it synchronously to Segment server, probably delaying the response on the app.

Also, when logging out, I recommend to perform a FlushAsync so as to be certain that all Actions of a user are sent to Segment server. Even though, flushing is called when 10000 actions are added in the queue, if you do not reached that amount when logging out, it won't perform the flushing. If you log in again and you fill the remaining amount of spaces in the queue with more actions then yes it will send automatically to the server the actions when dequeing.

I hope you find this information helpful.

**Comment by pmahend1** [comment]
I am sorry I don't understand.
Async = False  = means synchronous mode, events are sent as soon as they are fired

Async=True= means asynchronous
Based on the code I read from your repo(AsyncFlush handler or something) it seems it is called every 10 seconds by default,also there is FlushAt which is defaulted to 20. So I assume Flush operation is carried out every 10 seconds or when queue is 20 whichever is first.
From my understanding I do not think Max quue is the maximum number of events by default it can have.If there will be 10001 events in 10 seconds then only 10000 are counted.In that case we can change the default per our needs. 

By action do you mean the event that is in segment queue?

I am calling FlushAsync at logout parallelly.

I will check if I can add when the app is closed as well.
