### ISSUE TITLE
`Defaults` class removed with no way to access values elsewhere

### ISSUE THREAD

**Issue by anorborg** [segmentio/Analytics.NET#170]
This PR: https://github.com/segmentio/Analytics.NET/pull/131 removes the Defaults suggesting the values can be known at the moment of configuration. However, several of the `Config` class properties (such as `MaxQueueSize`) are marked internal.

**Comment by juliette-ruchel** [comment]
Hi @anorborg , we have just added Get functionality to the Config's properties so as you can retrieve current values. We kept the properties internal so as to avoid mistaken configuration to them using equal. Hope you find this functionality helpful.
