### ISSUE TITLE
Versioning Question Due to Error

### ISSUE THREAD

**Issue by spencerattick** [segmentio/Analytics.NET#176]
Hey Team! 

I'm working with a customer who is trying to get up and running with the Analytics.NET library. They are hitting an error that looks to be due to versioning. Could you clarify the following to see if it clears up their issue?

1. Are they required to use the same version of the .NET Framework Segment uses?

2. Is it recommended/usual practice to compile their own version of the Segment library from your repository, against the same version of the .NET Framework that they're using?

The issue they're running into is as follows where <client DLL path> is the path to their project and <client DLL name> is the name of the DLL:

```
There was a conflict between "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

"System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.

References which depend on "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll].

        C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll

          Project file item includes which caused reference "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Net.Http.dll".

            System.Net.Http

References which depend on "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [<client DLL path>\bin\Debug\System.Net.Http.dll].

        <client DLL path>\bin\Debug\Analytics.dll

         Project file item includes which caused reference "<client DLL path>\bin\Debug\Analytics.dll".

            <client DLL path>\bin\Debug\iwObjects.dll

        <client DLL path>\bin\Debug\netstandard.dll

          Project file item includes which caused reference "<client DLL path>\bin\Debug\netstandard.dll".

            <client DLL path>\bin\Debug\<client DLL name>.dll
```

 Thanks!

**Comment by juliette-ruchel** [comment]
Hi @spencerattick, I will answer your questions below:

1.  Yes, although Analytics.NET is compatible with .NET standard 1.3 and 2.0 which makes it suitable to use with framework 4.6.x and above versions of .NET framework.
2. No, you should be able to add segment library as a nuget package and should work well with the solution when you add it if it complies with allowed compatible frameworks in the library. Specifically talking, it should work with Framework 3.5, 4.5, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8. Also, before installing as a nuget package, check on Dependencies restrictions, perhaps the reference you are trying to add in your solution is not compatible with the library restriction Analytics.NET has.

Nevertheless, I see you are using .NET Framework 4.6.1 so I will be looking into the System.Net.Http.dll compatibility restrictions to see if I find a restriction problem.

**Comment by spencerattick** [comment]
Thanks for much for taking a look @juliette-ruchel! 🎉

**Comment by juliette-ruchel** [comment]
Hi @spencerattick, Have been taking a look at the System.NET.Http.dll problem. It does not seem to be an issue regarding the Segment library. 

Looking into the reference problem itself, I found that perhaps your customer is using visual studio 2017 to develop their application. It seems Microsoft had some issues regarding reference problems with this version of Visual Studio and perhaps your customer should try to remove the default reference of System.Net.Http added to the project and try to install it using nuget package. 

Let me know if you are able to fix the issue.

**Comment by nd4p90x** [comment]
@spencerattick Please re-open if there are more concerns regarding this issue.  Thank you.
