### ISSUE TITLE
AsyncIntervalFlushHandler deadlock

### ISSUE THREAD

**Issue by tpiriyakulchai** [segmentio/Analytics.NET#188]
Hi,

We are trying to upgrade `Analytics.Net` from version **2.0.3** => **3.8.0** on our .Net Framework web applications. However, we ran into a deadlock after that. I have investigated the issue and found that the cause was the `AsyncIntervalFlushHandler`.

https://github.com/segmentio/Analytics.NET/blob/452a4e060db3ebaf435be198895e022c9efa2b41/Analytics/Flush/AsyncIntervalFlushHandler.cs#L88

We are using the Synchronous `Flush()` method in the `AsyncIntervalFlushHandler` since it's currently not easy to convert our code that use the library into full asynchronous. Then, unfortunately, we hit the deadlock. We found that the implementation of the synchronous `Flush()` method is still calling the `FlushAsync()` synchronously using `GetAwaiter().GetResult()`. The `FlushAsync()`, although using `ConfigureAwait(false)` on the surface, not using `ConfigureAwait(false)` all the way through to the bottom of the asynchronous flow. That caused the classic deadlock issue.

Therefore, I wonder if it's possible for you to update the code and put `ConfigureAwait(false)` all the way down to the bottom?

**Comment by imedoc2023** [comment]
Hi @tpiriyakulchai,

Have you tried setting the Async property of the Config element to false? If you want to keep using your code synchronously, try using Segment library like this:

var config =  new Config().SetAsync(false);
Analytics.Initialize("WRITE_KEY", config);

Using it like that, will make Segment library make the request to Segment's as soon as you call an action (Track, Page, Screen, etc). It will not enqueue it, so you will not need to use Flush().

Hope this is helpful for you.

**Comment by tpiriyakulchai** [comment]
Hi @imedoc2023,

Thanks for getting back to me!

Yes, we have discovered that option and have considered using it. It would work, however, we were afraid that we would send many more API requests with that option as we wouldn't send the data in batches anymore. (happy to be wrong) If that's the case, do you reckon if that would increase our cost, or if we would hit a rate limit?

**Comment by nd4p90x** [comment]
@tpiriyakulchai After discussing this issue internally, you should not see any increase in costs if you send requests without a batch process.  Let me know if you have any other questions and I will be happy to address them.  

Thank you.
