### ISSUE TITLE
Encounter System.ObjectDisposedException after Dispose is called

### ISSUE THREAD

**Issue by pickchen-ong** [segmentio/Analytics.NET#189]
Hi, 

We have encountered "System.ObjectDisposedException: 'Safe handle has been closed'" after calling Dispose();

It was triggered by the timer callback "PerformFlush" in AsyncIntervalFlushHandler.cs

private void RunInterval()
{
   var initialDelay = _queue.Count == 0 ? _flushIntervalInMillis : 0;
   _timer = new Timer(new TimerCallback(async (b) => await PerformFlush()), new { }, initialDelay, _flushIntervalInMillis);
}

Is there a way to stop timer before dispose?

**Comment by JT-Bruch** [comment]
This is still occurring occasionally for us. 

![image](https://user-images.githubusercontent.com/7430562/172179949-b647710a-9469-4d43-9760-f1f6418f8201.png)
