### ISSUE TITLE
Snyk.io reports issue with referenced Newtonsoft.Json package

### ISSUE THREAD

**Issue by algonzalez-wf** [segmentio/Analytics.NET#194]
I ran the Snyk.io analyzer on a project referencing the Analytics (v3.8.0) package and it reports the version of Newtonsoft.Json (v12.0.3) referenced has an "Insecure Defaults [High Severity]" issue. This issue is fixed in v13.0.1 of the Newtonsoft.Json package. 

I did notice it was already bumped to v13.0.1 in the Analytics.csproj on 14-Jul-2022 by dependabot.

I was wondering what the process and cadence are for the next release of the Analytics package using the newer version of Newtonsoft.Json? 

Thanks

**Comment by spencerattick** [comment]
Hey folks! Thanks for taking a look at this one. Based on what you've shared, it looks like there is a 3.8.1 version available with the necessary Newtonsoft.Json update. Could you make it available on Nuget as well as updating the docs? 🙏
