### ISSUE TITLE
Make it easier to get 'hidden' errors when trying to send data to Segment

### ISSUE THREAD

**Issue by PureKrome** [segmentio/Analytics.NET#198]
G'day 👋🏻 

Recently, I was trying to send data to Segment from my localhost development machine and nothing was getting recorded @ segment. I double checked things like my secret keys, etc.

I finally stumbled onto _this clue_ :

![image](https://user-images.githubusercontent.com/899878/179164896-509154c2-ddb9-4310-8c17-171717a48abf.png)

Which ment "something" was failing/erroring! But .. I couldn't figure out what/where/how/etc ...

It would be nice if there some documentation about this (maybe there is, but hidden?) or some extra information could be exposed / lit-up to help diagnose such problems and save some time?

FYI, the issue was that I have [Pi-Hole](https://pi-hole.net/) running (in my LAN) which is a advertisment-blocking system. `api.segment.io` was getting autoblocked. I figure this out when I noticed no traffic was going there (used "Fiddler" to snoop traffic) and then tried `ping` and that returned `Ping request could not find host api.segment.io. Please check the name and try again.` Solution was to accept-list your domain.

**Comment by edsonjab** [comment]
Here we have the documentation about how to use logging

https://segment.com/docs/connections/sources/catalog/libraries/server/net/#logging
