### ISSUE TITLE
Calling Analytics.Client.Flush() when there are pending events can cause deadlock

### ISSUE THREAD

**Issue by tombogle** [segmentio/Analytics.NET#200]
This problem is illustrated here: https://github.com/sillsdev/DesktopAnalytics.net/pull/27
To reproduce:

1. Build the SampleAppWithForm project
2. Run SampleAppWithForm
3. Click the Track button
4. Without delay, select the Flush checkbox
5. Click the X to close the window.
6. 
The call to Analytics.Client.Flush() never returns, and the window never closes.

**Comment by jasonleenaylor** [comment]
I've also seen this in a project, but didn't have consistent steps to reproduce.

**Comment by edsonjab** [comment]
Thanks for your report, we start looking into this

**Comment by edsonjab** [comment]
Hi @tombogle I tried replicate the issue but I don't have success, could you help us sharing your example project on a public repo, please?

**Comment by tombogle** [comment]
The repo linked above is public.

**Comment by edsonjab** [comment]
Hi @tombogle we identify on which place is the possible issue, we still working on your issue reported

**Comment by edsonjab** [comment]
Hi @tombogle we created a new LIB that you can use for your project, [CSharp](https://github.com/segmentio/Analytics-CSharp) in this library fixed the issue.
