### ISSUE TITLE
Why is the NuGet package unlisted?

### ISSUE THREAD

**Issue by squid-box** [segmentio/Analytics.NET#202]
By chance I stumbled on the NuGet.org page for the [Analytics package](https://www.nuget.org/packages/Analytics), and saw the big sign stating it has been unlisted / has no owners.

![image](https://user-images.githubusercontent.com/864820/201374153-81d441b7-e468-4457-88b4-c8441424240c.png)

Should we discontinue use of this package? What's the recommendation here?

**Comment by edsonjab** [comment]
Hi @squid-box, we created a new LIB that you can use for your project, [CSharp](https://github.com/segmentio/Analytics-CSharp).

**Comment by squid-box** [comment]
Hi @edsonjab, thanks for the quick response!

I can't seem to find that library on NuGet, and the project description seems to indicate it is not yet ready for production use?

![image](https://user-images.githubusercontent.com/864820/201384626-289f1819-0643-47e5-9553-6bbcbdce32b3.png)

**Comment by edsonjab** [comment]
We are looking into it. The library will be available for prod soon.

**Comment by nd4p90x** [comment]
Looks like everything is back online: https://www.nuget.org/packages/Analytics

Sorry for any inconvenience 

Thank you
