### ISSUE TITLE
Analytics.NET Midleware

### ISSUE THREAD

**Issue by EricLacroix** [segmentio/Analytics.NET#203]
Is there a comparable way with the .Net version of Analytic to achieve more or less the same behavior found in the Analytics.Js version? https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/middleware/

**Comment by edsonjab** [comment]
Hi @EricLacroix we created a new library [CSharp](https://github.com/segmentio/Analytics-CSharp) you can check if it solves your problem
