### ISSUE TITLE
Making flushing thread a background thread.

### ISSUE THREAD

**Issue by Yrlec** [segmentio/Analytics.NET#22]
Hi,
My company is using your library in a console that we run as a nightly job. Today I noticed that the background job no longer shuts down properly. After running NewRelic's thread profiler in production I noticed that thread that was still running:

System.Threading.ThreadHelper:ThreadStart
System.Threading.ExecutionContext:Run
System.Threading.ExecutionContext:Run
System.Threading.ExecutionContext:RunInternal
System.Threading.ThreadHelper:ThreadStart_Context
Segmentio.Flush.AsyncFlushHandler:Loop
Segmentio.Flush.BlockingQueue`1:Dequeue
System.Threading.Monitor:Wait
System.Threading.Monitor:Wait

I'm guessing that this thread is not running with IsBackground set to true? http://msdn.microsoft.com/en-us/library/system.threading.thread.isbackground(v=vs.110).aspx

I'd very much appreciate if you would change that. Thanks!

**Comment by BerkanYildiz** [comment]
Bump, it's still a problem to this day
