### ISSUE TITLE
Identify call without userId?

### ISSUE THREAD

**Issue by jdconley** [segmentio/Analytics.NET#25]
We use some integrations that take advantage of identify calls without user id's (Drip, Salesforce). These work fine in Analytics.js, but this .NET client throws an InvalidOperationException if you attempt to call Identify without the userId parameter. Is there some way to mimic the behavior in Analytics.JS so we can call this before we have a User Id in our system?

**Comment by f2prateek** [comment]
This is on master https://github.com/segmentio/Analytics.NET/commit/7a0c4741b0900d0ce670df40103d7f6967c89113

**Comment by jdconley** [comment]
So there needs to be an options.anonymousId. How do we grab that from the browser?

**Comment by jdconley** [comment]
Nvm, found it. https://segment.com/docs/libraries/analytics.js/#anonymous-id

**Comment by jdconley** [comment]
Looks like this option is available for every call _except_ Identify: https://github.com/segmentio/Analytics.NET/blob/master/Analytics/Client.cs#L130

**Comment by jdconley** [comment]
Created pull #26 for this

**Comment by jdconley** [comment]
Any chance you can version and push a nuget release for this soon? Much easier to deal with deps that way.

**Comment by f2prateek** [comment]
Released with 2.0.2
