### ISSUE TITLE
Incompatible with the Universal Windows Platform 

### ISSUE THREAD

**Issue by ladanazita** [segmentio/Analytics.NET#31]
Developing a Windows 10 Phone App, using the Universal Windows Platform and installing with NuGet results in this error:

"Install-Package : Analytics 2.0.2 is not compatible with UAP,Version=v10.0."

**Comment by mjracca** [comment]
I aslo want use Segment in a Windows 10 application, and have the same issue.

**Comment by mjracca** [comment]
I just successfully added https://segment.com/docs/libraries/xamarin/ to my UAP app. Should we use Xamarin library instead of this one?

**Comment by f2prateek** [comment]
yes, this library is not meant for xamarin's universal app platform.

**Comment by mjracca** [comment]
We were talking about Windows 10 Universal Apps, not Xamarin apps

**Comment by kristinnv12** [comment]
@f2prateek I am not developing a Xamarin app, but a Windows 10 Universal App. Wich library should I use?
