### ISSUE TITLE
Inconsistent phrasing in error messages for public methods of class Client

### ISSUE THREAD

**Issue by Dmitry-Me** [segmentio/Analytics.NET#40]
class `Client` has a number of methods which accept `userId` and a second parameter which varies from one method to another. Validation code uses line like this to throw:

     throw new InvalidOperationException("Please supply a valid userId or anonymousId to SOMETHING.");

and

     throw new InvalidOperationException("Please supply a valid PARAMNAME to SOMETHING");

Although only method names should differ the actual wording for SOMETHING is inconsistent.

1. `Group()` says `to call #Group` for both checks.
2. `Track()` says `to Track` - no "call" and no `#`.
3. `Page()` says `to #Page` - no "call"
4. `Screen()` says `to #Screen` - no "call"

**Comment by f2prateek** [comment]
Seems reasonable, happy to accept a PR to standardize it!

**Comment by Dmitry-Me** [comment]
@f2prateek It looks like you don't accept PRs often https://github.com/segmentio/Analytics.NET/pull/35

**Comment by f2prateek** [comment]
@Dmitry-Me sorry that slipped under the radar, thanks for bringing it up!

**Comment by f2prateek** [comment]
Closed by #43
