### ISSUE TITLE
Statistics signed integers blindly incremented

### ISSUE THREAD

**Issue by Dmitry-Me** [segmentio/Analytics.NET#41]
Here's the definition of `Statistics`:

    public class Statistics
    {
        public int Submitted { get; set; }
        public int Succeeded { get; set; }
        public int Failed { get; set; }
    }

All members are signed. The typical line of code dealing with them looks like this:

    _client.Statistics.Failed += 1;

If code runs long enough then counters may reach `Int32.MaxValue`. Depending on whether code runs in checked or unchecked context subsequent behavior varies. If code happens to run in unchecked context then counters overflow and become negative which makes no sense. If code happens to run in checked context then subsequent increments fail with `OverflowException`.

Counters should be unsigned. Code manipulating them should be explicitly wrapped in `unchecked {}`.

**Comment by f2prateek** [comment]
In practice this hasn't been a problem. A 32 bit signed int can count upto 2 billion events. But wouldn't be unreasonable to bump it to unsigned.

**Comment by Dmitry-Me** [comment]
@f2prateek Changing it to unsigned is not enough, the increment should be done in unchecked context, otherwise there's an exception when it tries to increment past four billions.

**Comment by f2prateek** [comment]
Yup - but again as I said, this hasn't been a problem in practice. Happy to accept a PR though!
