### ISSUE TITLE
Tracking events that occur when no network connection is available are discarded

### ISSUE THREAD

**Issue by leankitryan** [segmentio/Analytics.NET#42]
In testing Segment Analytics on mobile devices under Xamarin, I've noticed any events that occur while the device is offline are discarded. It appears the event queue is being flushed even if the events fail to send to segment.io.

```
[Analytics] [DEBUG] Dequeued action in async loop. message id: d0fe64a7-7715-465a-bf4a-08f8189dba3d, queue size: 0,
[Analytics] [DEBUG] Created flush batch. batch size: 1,
[Analytics] [INFO] Sending analytics request to Segment.io .. batch id: f552873c-7656-485c-83e9-f79c22c15809, json size: 513, batch size: 1,
[Analytics] [DEBUG] Enqueued action in queue. queue size: 0,
[Analytics] [INFO] Segment.io request failed. batch id: f552873c-7656-485c-83e9-f79c22c15809, reason: Error: ConnectFailure (Network is unreachable), duration (ms): 0,
[Analytics] [DEBUG] Queue is empty, flushing is finished.
```

In a server environment this might not be a big deal but on mobile devices which frequently lose connection it seems a more robust queuing strategy is needed.  Other analytics libraries I've used such as Xamarin Insights and Google Analytics have this capability.

**Comment by f2prateek** [comment]
Was this meant for Analytics.Xamarin https://github.com/segmentio/Analytics.Xamarin? This library is currently not designed to be used in mobile environments.

**Comment by leankitryan** [comment]
it was, sorry.
