### ISSUE TITLE
Segment now breaks on reference in CLS-compliant .NET platforms

### ISSUE THREAD

**Issue by jzebedee** [segmentio/Analytics.NET#46]
@f2prateek @Dmitry-Me I think there are some problems with PR #41. Adding the `unchecked` blocks is unnecessary, but harmless, since the default behavior is to silently overflow:

> For non-constant expressions (expressions that are evaluated at run-time) that are not enclosed by any checked or unchecked operators or statements, the default overflow checking context is unchecked unless external factors (such as compiler switches and execution environment configuration) call for checked evaluation.
- from the [C# specification on `checked`](https://msdn.microsoft.com/en-us/library/aa691349(v=vs.71).aspx)

**However, changing the properties from `int` to `uint` will break [CLS compliance](http://stackoverflow.com/a/6333/102351) ([MSDN](https://msdn.microsoft.com/en-us/library/12a7a7h3.aspx)), which is a huge deal for a library project**. As of this change, any code written in a .NET language that doesn't support `uint`s will break on reference once this goes out.

**Comment by Dmitry-Me** [comment]
@f2prateek I guess this is sensible approach yet this will look rather overengineered. Do you want another PR.

**Comment by f2prateek** [comment]
That'd definitely be great, thanks! I do agree the solution won't look pretty - definitely open to other  ideas as well.

**Comment by Dmitry-Me** [comment]
@f2prateek @jzebedee  Submitted https://github.com/segmentio/Analytics.NET/pull/48
