### ISSUE TITLE
Support through a proxy?

### ISSUE THREAD

**Issue by rmariotti-choicelunch** [segmentio/Analytics.NET#49]
I'm trying to see how I could update my .NET server-to-server code to send the Segment Identify and Track requests through a proxy.  

We're moving to a more secure environment that requires outbound calls from the API server to pass through a proxy.  Thank you for the info; we love Segment!

Ryan

**Comment by f2prateek** [comment]
We'd have to make the Host public https://github.com/segmentio/Analytics.NET/blob/86327620f408f4d67ba57a7ecf153552330ac858/Analytics/Config.cs#L17.

**Comment by rmariotti-choicelunch** [comment]
@f2prateek - I see that Host is just a string.  Would additional properties be needed to be able to set Proxy as an object on some HttpWebRequest?  

How would such an enhancement be approved and built into Analytics.NET?  Thanks for the info!
Ryan

**Comment by f2prateek** [comment]
Nope, just making it public should work. Internally, the library uses that to figure out the full URL to send data to: https://github.com/segmentio/Analytics.NET/blob/76bdd0dba41b4763427ecebc276cc289f7ca1140/Analytics/Request/BlockingRequestHandler.cs#L51.

So if you set host to `mydomain.com`, we'll send data to `mydomain.com/v1/import`.

**Comment by f2prateek** [comment]
And yes, we'll be open to accepting this change :D

**Comment by rmariotti-choicelunch** [comment]
I'm still not 100% on how this accomplishes a Proxy though, @f2prateek.  I thought you needed TWO URLs:

1) URL of the target destination (e.g. Segment's API server)
2) URL of the proxy that the request has to go through

With only `Host`, I guess I would have to set it to `myproxy.com`, resulting in `myproxy.com/v1/import` and the proxy would have to be smart enough to forward that request, based on part of the path, to the Segment API server.  (??)

**Comment by f2prateek** [comment]
> With only Host, I guess I would have to set it to myproxy.com, resulting in myproxy.com/v1/import and the proxy would have to be smart enough to forward that request, based on part of the path, to the Segment API server. (??)

Correct, I was going off the assumption that this proxy is dedicated to Segment and uses something like  https://github.com/segmentio/segment-proxy. 

In this case, your client only cares about sending the data to your proxy (i.e. #2), your proxy is responsible for choosing where to forward it next (i.e. #1).  The client doesn't tell it where to forward to next, the proxy is configured independently to do that.

But you're right, it would depend on the proxy. Though I would recommend controlling #1 on the proxy, as it gives you the ability to change where the proxy is directing the events to without redeploying your clients.

**Comment by f2prateek** [comment]
Closed by https://github.com/segmentio/Analytics.NET/pull/64
