### ISSUE TITLE
Support .NETStandard,Version=v1.4

### ISSUE THREAD

**Issue by Lapinou42** [segmentio/Analytics.NET#50]
Hello, 

It would be greate to support .NETStandard,Version=v1.4 :)

Thank you,
Lapinou.

**Comment by spewu** [comment]
I made a pull request for targeting netstandard 1.3: https://github.com/segmentio/Analytics.NET/pull/51

**Comment by Lapinou42** [comment]
@spewu Thank you ! 👍

**Comment by f2prateek** [comment]
This should be done as of 3.1.0-alpha.
