### ISSUE TITLE
Publish non-alpha Package v2

### ISSUE THREAD

**Issue by michaeljfarr** [segmentio/Analytics.NET#87]
Its been a couple of months-ish since clfetchers original question so I thought I'd ask again.  Those of us that really need .net standard support would really like to see a non-alpha library for Segment up on Nuget, is this something you could see happening in the near future?

I can see some quite sensible PRs from daletskyi that are waiting for approval still.  Perhaps we could at least have a 3.4.0 alpha library on nuget with those fixes in?

**Comment by f2prateek** [comment]
If you need .NET standard support, I would recommend using the alpha versions. We generally don't promote versions until we see a significant amount of traffic going through those versions. We have a much higher bar for this release especially because of the scope of the changes that are included.
