### ISSUE TITLE
Writekey displayed in Segment data object

### ISSUE THREAD

**Issue by sandarsh-sridhar-cliq** [segmentio/Analytics.NET#98]
When using 'track' or 'identify', write key is also displayed in the segment event data. 
Is there a specific reason for this?
I understand that write key is required to make an authentication token while posting to Segment API endpoint. But it only needs to be in the http-client headers. Or is there something I am missing here?

**Comment by f2prateek** [comment]
hey @sandarsh-sridhar-cliq the library sends the data as an authorization header (https://github.com/segmentio/Analytics.NET/blob/8d0b148bb4ff7c5741744de3b7f155ca84cddbd8/Analytics/Request/BlockingRequestHandler.cs#L138). I believe it's the API and debugger that maybe show this in the body - I might suggest you write in via our support form so our support team can get the right team to answer this!

**Comment by sandarsh-sridhar-cliq** [comment]
Thank you for responding to the issue this quickly. I had gone through that snippet of code. It absolutely makes sense to have the write key in a strongly typed class. But that property can be ignored during serialization with JsonIgnore property from Newtonsoft.json, so that it doesn't make it to the event data itself.

**Comment by f2prateek** [comment]
Ah... I see what you mean. It's because we convert the `batch` object to JSON directly here https://github.com/segmentio/Analytics.NET/blob/8d0b148bb4ff7c5741744de3b7f155ca84cddbd8/Analytics/Request/BlockingRequestHandler.cs#L133, causing the writeKey to be sent.

**Comment by sandarsh-sridhar-cliq** [comment]
That's correct. So, when you annotate the WriteKey property with JsonIgnore, it wouldn't make it to the payload but you will still be able to make the POST request.

**Comment by sandarsh-sridhar-cliq** [comment]
Thank you. I appreciate it. :)

**Comment by sandarsh-sridhar-cliq** [comment]
Hmm...That's interesting. Well, thank you for trying though. Yeah, I shall open a support issue.
Thanks again.

**Comment by nd4p90x** [comment]
Confirmed that the writeKey is not being displayed in the current version, Thank you.
